name: CI - Test & Package Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write .env file from secret
      run: echo "${{ secrets.DOTENV_FILE }}" > .env

    - name: Run unit tests
      run: pytest tests/test_s3_service.py

    - name: Package project
      run: |
        mkdir dist
        zip -r dist/filesharing-release.zip app .env requirements.txt

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: filesharing-release
        path: dist/filesharing-release.zip
