name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI - Test & Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest tests/unit

    - name: Write .env file from secret
      run: echo "${{ secrets.DOTENV_FILE }}" > .env

    - name: Archive project
      run: zip -r app.zip app .env requirements.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-package
        path: app.zip

  cd:
    name: CD - Deploy to EC2
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-package
        path: .

    - name: Upload to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app.zip"
        target: "/home/${{ secrets.EC2_USER }}/deploy"

    - name: Remote deploy command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/deploy
          unzip -o app.zip
          pkill uvicorn || true
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 &
          echo "Deployed commit $GITHUB_SHA at $(date)" >> deploy.log
